In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("train.csv")

In [4]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df=pd.read_csv("train.csv",usecols=['X1','X2','X3','X4','X5','X6','X8'])

In [6]:
df.head()

  X1  X2 X3 X4 X5 X6 X8
0  v  at  a  d  u  j  o
1  t  av  e  d  y  l  o
2  w   n  c  d  x  j  x
3  t   n  f  d  x  l  e
4  v   n  f  d  h  d  n

In [7]:
for col in df.columns:
    print(col, ":",len(df[col].unique()),"labels" )

X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels
X6 : 12 labels
X8 : 25 labels

In [9]:
pd.get_dummies(df,drop_first=True).shape

(4209, 141)

In [24]:
#finding most frequent categories fro the variable
df.X2.value_counts().sort_values(ascending=False).head(40)

as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
i       25
k       25
b       21
ao      20
z       19
ag      19
d       18
ac      13
g       12
ap      11
y       11
x       10
aw       8
h        6
at       6
an       5
q        5
al       5
p        4
ah       4
av       4
au       3
j        1
aa       1
af       1
c        1
Name: X2, dtype: int64

In [16]:
#inorder to make data clean and reliablity we have to seletect the proper
#in 
top_10 =[X for X in df.X2.value_counts().sort_values(ascending=False).head(20).index]

In [23]:
#below function says that
#taking top_10 labels if found make it 1 others value = 0

for label in top_10:
    df[label]= np.where(df['X2']==label,1,0)
df[['X2']+top_10].head(40)

    X2  as  ae  ai  m  ak  r  n  s  f  ...  aq  ay  a  t  i  k  b  ao  z  ag
0   at   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
1   av   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
2    n   0   0   0  0   0  0  1  0  0  ...   0   0  0  0  0  0  0   0  0   0
3    n   0   0   0  0   0  0  1  0  0  ...   0   0  0  0  0  0  0   0  0   0
4    n   0   0   0  0   0  0  1  0  0  ...   0   0  0  0  0  0  0   0  0   0
5    e   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
6    e   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
7   as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
8   as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
9   aq   0   0   0  0   0  0  0  0  0  ...   1   0  0  0  0  0  0   0  0   0
10   r   0   0   0  0   0  1  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
11   e   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
12  ai   0   0   1  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
13   e   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
14  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
15  ak   0   0   0  0   1  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
16   e   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
17  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
18   m   0   0   0  1   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
19  ak   0   0   0  0   1  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
20   m   0   0   0  1   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
21  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
22   a   0   0   0  0   0  0  0  0  0  ...   0   0  1  0  0  0  0   0  0   0
23   m   0   0   0  1   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
24  ak   0   0   0  0   1  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
25   m   0   0   0  1   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
26  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
27  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
28  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
29   m   0   0   0  1   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
30  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
31  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
32   m   0   0   0  1   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
33  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
34  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
35  ai   0   0   1  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
36  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
37   k   0   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  1  0   0  0   0
38  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0
39  as   1   0   0  0   0  0  0  0  0  ...   0   0  0  0  0  0  0   0  0   0

[40 rows x 21 columns]

In [32]:
#get whole set of dummy variable for all categories
#variable

def one_hot_top_x(df,variable,top_x_labels):
    #function to create the dummy varibles for the most frequent label
    #we can vary the number of mst frequent lables that we encode
    
    
    for label in top_x_labels:
        df[variable+' '+label]=np.where(data[variable]==label ,1,0)
        
data= pd.read_csv("train.csv",usecols=["X2","X4","X5","X6","X8"]) 

#encode x2 into the most frequent categories
X2=one_hot_top_x(data,'X2',top_10)
X4=one_hot_top_x(data,'X4',top_10)
X5=one_hot_top_x(data,'X5',top_10)
X6=one_hot_top_x(data,'X6',top_10)
data.head()

,X2,X4,X5,X6,X8,X2 as,X2 ae,X2 ai,X2 m,X2 ak,...,X6 aq,X6 ay,X6 a,X6 t,X6 i,X6 k,X6 b,X6 ao,X6 z,X6 ag
0,at,d,u,j,o,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,av,d,y,l,o,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,n,d,x,j,x,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,n,d,x,l,e,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,n,d,h,d,n,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0